#!/usr/bin/env python
def _pythonrc():
    
    import atexit
    import os
    import readline
    
    if 'libedit' in readline.__doc__: readline.parse_and_bind("bind ^I rl_complete")
    else: readline.parse_and_bind("tab: complete")
    
    history = os.path.expanduser("~/.py_history")
    readline.set_history_length(500)
    if os.path.exists(history): readline.read_history_file(history)
    
    @atexit.register
    def write_history(history=history):
        readline.write_history_file(history)


_pythonrc()

del _pythonrc
