#!/bin/bash

# A simple interface for mpd using dmenu.

if [ -f $HOME/.dmenurc ]; then
    . $HOME/.dmenurc
else
    DMENU='dmenu -i'
fi
#$( echo -e "Play All\n$( mpc ls "$ARTIST" )"

artist=$( echo -e "Next\nPause\n$(mpc list artist| sort -n)"| $DMENU -i -l 10)
dmError=$?

if [[ $dmError -ne 0 ]]; then
    echo "no song! nothing happening"
    exit 1
fi

if [[ $artist = 'Pause' ]]; then
    echo "pausing..."
    mpc status | grep "\[playing\]"
    mpdstatus=$?
    if [[ $mpdstatus = 0 ]]; then
        mpc pause
        exit
    else
        mpc play
        exit
    fi
fi

if [[ $artist = 'Next' ]]; then
    echo "next track..."
    mpc next
    exit
fi

if [[ $artist = '' ]]; then
    echo "playing everything"
    mpc ls | mpc add; mpc shuffle && mpc next
    exit
else
    if [[ $(mpc list album artist "$artist" | wc -l) > 1 ]]; then
        album=$( echo -e "All\n$(mpc list album artist "$artist")"| sort -n | \
        $DMENU -i -p "ALBUM:" -l 4)
        mpdstatus=$?
    fi

    if [[ $mpdstatus -ne 0 ]]; then
            exit 1
    fi

    mpc clear >> /dev/null

if [[ $album = 'All' ]]; then
    echo "Playlist cleared, Adding all songs available from $artist to the playlist"
    mpc find artist "$artist" | mpc add
else
    echo "Playlist cleared, Adding $artist - $album to the playlist"
    mpc find artist "$artist" album "$album" | mpc add

fi
    mpc play >> /dev/null
fi

exit 0
